// File generated by FlutterFire CLI.
// Jalankan: flutterfire configure
// File ini akan auto-generate setelah menjalankan command di atas

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] untuk Android.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android; // Android configuration
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2UrJSUXAnxNuqoLt265qHBTcZh8wdR4A',
    appId: '1:687933984929:android:e7fc5e80d486d5e27ca0e0',
    messagingSenderId: '687933984929',
    projectId: 'smartwaste-61572',
    storageBucket: 'smartwaste-61572.firebasestorage.app',
  );
}
